steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/fusion-prime/services/escrow-event-relayer-prod:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/fusion-prime/services/escrow-event-relayer-prod:latest'
    id: 'push-image'

  # Deploy to Cloud Run Service (continuous relayer)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'escrow-event-relayer-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/services/escrow-event-relayer-prod:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CHAIN_ID=11155111,RPC_URL=https://spectrum-01.simplystaking.xyz/Y2J1emtmcWQtMDEtMjJjN2I0YTE/6CuZK_q3OlibSg/ethereum/testnet/,CONTRACT_ADDRESS=0x311E63dfcEfe7f2c202715ef0DF01CDA82f58914,PUBSUB_PROJECT_ID=fusion-prime,PUBSUB_TOPIC_ID=settlement.events.v1,START_BLOCK=9525600,RELAYER_POLL_INTERVAL=5,RELAYER_BATCH_SIZE=50,RELAYER_CHECKPOINT_INTERVAL=25,MAX_CONCURRENT_REQUESTS=5,ESCROW_FACTORY_ABI_URL=gs://fusion-prime-contract-registry/contracts/dev/11155111/EscrowFactory.json,ESCROW_ABI_URL=gs://fusion-prime-contract-registry/contracts/dev/11155111/Escrow.json'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--timeout'
      - '3600'
      - '--port'
      - '8080'
    id: 'deploy-service'

images:
  - 'us-central1-docker.pkg.dev/fusion-prime/services/escrow-event-relayer-prod:latest'

timeout: '1200s'
