# Settlement Service Database
module "cloudsql_settlement" {
  source = "../modules/cloudsql"

  project_id    = var.project_id
  region        = var.region
  instance_name = "fp-settlement-db"
  database_name = "settlement_db"
  app_user_name = "settlement_user"
  tier          = "db-f1-micro" # Smallest dev tier
  disk_size_gb  = 10

  # Network - must wait for VPC peering to be established
  vpc_network_id = module.network.private_vpc_connection

  # Credentials - auto-generated by module and stored in Secret Manager
  app_user_password                = "" # Empty string triggers auto-generation
  store_password_in_secret_manager = true

  # Development settings
  high_availability          = false # Disable HA for dev to reduce costs
  enable_deletion_protection = false # Allow deletion in dev environment
  environment                = "dev"

  # Database flags tuned for db-f1-micro (1GB RAM)
  database_flags = [
    {
      name  = "max_connections"
      value = "25" # Reduced for micro instance
    },
    {
      name  = "shared_buffers"
      value = "32768" # 32MB (in 8KB pages) - ~25% of RAM
    },
    {
      name  = "effective_cache_size"
      value = "65536" # 64MB (in 8KB pages) - within 13107-91750 range
    },
    {
      name  = "work_mem"
      value = "1024" # 1MB (in KB)
    },
    {
      name  = "maintenance_work_mem"
      value = "16384" # 16MB (in KB)
    },
    {
      name  = "log_min_duration_statement"
      value = "1000" # Log queries > 1 second
    },
  ]
}

# Risk Engine Service Database
module "cloudsql_risk_engine" {
  source = "../modules/cloudsql"

  project_id    = var.project_id
  region        = var.region
  instance_name = "fp-risk-db"
  database_name = "risk_db"
  app_user_name = "risk_user"
  tier          = "db-f1-micro" # Smallest dev tier
  disk_size_gb  = 10

  # Network - use same VPC as settlement service
  vpc_network_id = module.network.private_vpc_connection

  # Credentials - auto-generated by module and stored in Secret Manager
  app_user_password                = "" # Empty string triggers auto-generation
  store_password_in_secret_manager = true

  # Development settings
  high_availability          = false # Disable HA for dev to reduce costs
  enable_deletion_protection = false # Allow deletion in dev environment
  environment                = "dev"

  # Database flags tuned for db-f1-micro (1GB RAM)
  database_flags = [
    {
      name  = "max_connections"
      value = "25" # Reduced for micro instance
    },
    {
      name  = "shared_buffers"
      value = "32768" # 32MB (in 8KB pages) - ~25% of RAM
    },
    {
      name  = "effective_cache_size"
      value = "65536" # 64MB (in 8KB pages) - within 13107-91750 range
    },
    {
      name  = "work_mem"
      value = "1024" # 1MB (in KB)
    },
    {
      name  = "maintenance_work_mem"
      value = "16384" # 16MB (in KB)
    },
    {
      name  = "log_min_duration_statement"
      value = "1000" # Log queries > 1 second
    },
  ]
}

# Compliance Service Database
module "cloudsql_compliance" {
  source = "../modules/cloudsql"

  project_id    = var.project_id
  region        = var.region
  instance_name = "fp-compliance-db"
  database_name = "compliance_db"
  app_user_name = "compliance_user"
  tier          = "db-f1-micro" # Smallest dev tier
  disk_size_gb  = 10

  # Network - use same VPC as other services
  vpc_network_id = module.network.private_vpc_connection

  # Credentials - auto-generated by module and stored in Secret Manager
  app_user_password                = "" # Empty string triggers auto-generation
  store_password_in_secret_manager = true

  # Development settings
  high_availability          = false # Disable HA for dev to reduce costs
  enable_deletion_protection = false # Allow deletion in dev environment
  environment                = "dev"

  # Database flags tuned for db-f1-micro (1GB RAM)
  database_flags = [
    {
      name  = "max_connections"
      value = "25" # Reduced for micro instance
    },
    {
      name  = "shared_buffers"
      value = "32768" # 32MB (in 8KB pages) - ~25% of RAM
    },
    {
      name  = "effective_cache_size"
      value = "65536" # 64MB (in 8KB pages) - within 13107-91750 range
    },
    {
      name  = "work_mem"
      value = "1024" # 1MB (in KB)
    },
    {
      name  = "maintenance_work_mem"
      value = "16384" # 16MB (in KB)
    },
    {
      name  = "log_min_duration_statement"
      value = "1000" # Log queries > 1 second
    },
  ]
}

# Price Oracle and Alert Notification databases removed - those services don't use databases

# Fiat Gateway Service Database
module "cloudsql_fiat_gateway" {
  source = "../modules/cloudsql"

  project_id    = var.project_id
  region        = var.region
  instance_name = "fp-fiat-gateway-db"
  database_name = "fiat_gateway"
  app_user_name = "fiat_gateway_user"
  tier          = "db-f1-micro" # Smallest dev tier
  disk_size_gb  = 10

  # Network - use same VPC as other services
  vpc_network_id = module.network.private_vpc_connection

  # Credentials - auto-generated by module and stored in Secret Manager
  app_user_password                = "" # Empty string triggers auto-generation
  store_password_in_secret_manager = true

  # Development settings
  high_availability          = false # Disable HA for dev to reduce costs
  enable_deletion_protection = false # Allow deletion in dev environment
  environment                = "dev"

  # Database flags tuned for db-f1-micro (1GB RAM)
  database_flags = [
    {
      name  = "max_connections"
      value = "25" # Reduced for micro instance
    },
    {
      name  = "shared_buffers"
      value = "32768" # 32MB (in 8KB pages) - ~25% of RAM
    },
    {
      name  = "effective_cache_size"
      value = "65536" # 64MB (in 8KB pages) - within 13107-91750 range
    },
    {
      name  = "work_mem"
      value = "1024" # 1MB (in KB)
    },
    {
      name  = "maintenance_work_mem"
      value = "16384" # 16MB (in KB)
    },
    {
      name  = "log_min_duration_statement"
      value = "1000" # Log queries > 1 second
    },
  ]
}

# Cross-Chain Integration Service Database
module "cloudsql_cross_chain" {
  source = "../modules/cloudsql"

  project_id    = var.project_id
  region        = var.region
  instance_name = "fp-cross-chain-db"
  database_name = "cross_chain"
  app_user_name = "cross_chain_user"
  tier          = "db-f1-micro" # Smallest dev tier
  disk_size_gb  = 10

  # Network - use same VPC as other services
  vpc_network_id = module.network.private_vpc_connection

  # Credentials - auto-generated by module and stored in Secret Manager
  app_user_password                = "" # Empty string triggers auto-generation
  store_password_in_secret_manager = true

  # Development settings
  high_availability          = false # Disable HA for dev to reduce costs
  enable_deletion_protection = false # Allow deletion in dev environment
  environment                = "dev"

  # Database flags tuned for db-f1-micro (1GB RAM)
  database_flags = [
    {
      name  = "max_connections"
      value = "25" # Reduced for micro instance
    },
    {
      name  = "shared_buffers"
      value = "32768" # 32MB (in 8KB pages) - ~25% of RAM
    },
    {
      name  = "effective_cache_size"
      value = "65536" # 64MB (in 8KB pages) - within 13107-91750 range
    },
    {
      name  = "work_mem"
      value = "1024" # 1MB (in KB)
    },
    {
      name  = "maintenance_work_mem"
      value = "16384" # 16MB (in KB)
    },
    {
      name  = "log_min_duration_statement"
      value = "1000" # Log queries > 1 second
    },
  ]
}
