steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - >-
        apt-get update && apt-get install -y python3 python3-pip python3-venv &&
        pip3 install poetry &&
        poetry install --no-root &&
        poetry run pytest
timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud builds submit --config infra/cloud-build/schema-register.yaml .
